### ISSUE TITLE
svn: sqlite[S21]: library routine called out of sequence [Tigris #1613]

### ISSUE THREAD

**Issue by markphip** [subclipse/svnclientadapter#25]
## Description

    !ENTRY org.tigris.subversion.subclipse.core 4 -6 2015-01-22 15:21:33.475
    !MESSAGE org.apache.subversion.javahl.ClientException: SQLite error
    svn: sqlite[S21]: library routine called out of sequence
    
    !STACK 0
    org.tigris.subversion.svnclientadapter.SVNClientException:
    org.apache.subversion.javahl.ClientException: SQLite error
    svn: sqlite[S21]: library routine called out of sequence
    
            at
    org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.addFile(AbstractJhlClientAdapter.java:224)
            at
    org.tigris.subversion.subclipse.core.commands.AddResourcesCommand.run(AddResourcesCommand.java:144)
            at
    org.tigris.subversion.subclipse.core.SVNTeamProvider.add(SVNTeamProvider.java:124)
            at
    org.tigris.subversion.subclipse.ui.operations.CommitOperation.execute(CommitOperation.java:78)
            at
    org.tigris.subversion.subclipse.ui.operations.SVNOperation.run(SVNOperation.java:90)
            at
    org.eclipse.team.internal.ui.actions.JobRunnableContext.run(JobRunnableContext.java:144)
            at
    org.eclipse.team.internal.ui.actions.JobRunnableContext$ResourceJob.runInWorkspace(JobRunnableContext.java:72)
            at
    org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
            at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
    Caused by: org.apache.subversion.javahl.ClientException: SQLite error
    svn: sqlite[S21]: library routine called out of sequence
    
            at org.apache.subversion.javahl.SVNClient.add(Native Method)
            at org.apache.subversion.javahl.SVNClient.add(SVNClient.java:183)
            at
    org.tigris.subversion.svnclientadapter.javahl.AbstractJhlClientAdapter.addFile(AbstractJhlClientAdapter.java:221)
            ... 8 more

## Metadata Imported from Tigris (Issue 1613)

  * **Creation Date**: 2015-01-22 06:25:33
  * **Reporter**: subclipsebugs
  * **Subcomponent**: svnClientAdapter
  * **Version**: 1.8.x
  * **Milestone**: not determined
  * **Keywords**: 
  * **Cc**: 

### 2015-01-22 06:52:59 by markphip

    From the stack trace it looks like you are doing a commit and there were unversioned files included 
    that are being "add"ed to SVN on the fly so they can be part of the commit.  Is there anything else 
    you can add that would help reproduce the problem.  This is an error internal to the SVN API being 
    used so it will have to be reported upstream to get a fix or explanation.
    
    IOW, was it an entire unversioned tree of folders and files, just a file in a folder etc.
    
    Was SVNKit involved at all?  They had to write their own version of SQLite in Java so it is possible 
    there is some difference in the DB they created if you switched to JavaHL later.  JavaHL is native 
    Subversion which uses the native SQLite library.
    

### 2015-01-22 07:06:36 by subclipsebugs

    there has been involved one newly created file (Java class), everthing else had
    just changes in content.
    
    so, what you saying is, that as a workaround i should not depend on subclipse
    (or whoever does it) automatically adding the new file, but rather explicitly
    select Team -> Add to Version Control?
    
    i've used to use JavaHL all the time, then after an subclipse update it started
    to throw this error, thus i switched to SVNKit.
    SVNKit intermittendly fails to compare, so i switch to JavaHL to compare -- and
    if commit fails, back to SVNKit to commit.
    
    this issue also occurs only intermittendly, and so far i have been unable to
    determine a pattern.
    
    would it be possible to delete/recreate the SQLite db involved?

### 2015-01-22 07:11:04 by markphip

    I do not know if that would be a workaround, but you can try it.  Rather than ask you for a complete 
    reproduction recipe, I was simply articulating what can be seen by the stack trace.  The part I cannot 
    tell is what was being added.  Obviously, if it was just one new file then that is a pretty normal case, 
    so unlikely to be something that I or anyone else is going to be able to recreate.  So was hoping for 
    some more exotic scenario.
    
    My guess is that SVNKit did something to "corrupt" the SQLite DB as far as regular SQLite is 
    concerned.  In terms of creating a new DB, all you could do would be to do a new clean checkout 
    using JavaHL.
    
    SQLite itself might have some command line tools to check a DB or do stuff to it, but I am not familiar 
    with what that might be.

**Comment by markphip** [comment]
I have not seen this come up since, so closing.
